[package]
name = "user_lib"
version = "0.1.0"
authors = ["涂轶翔 <tyx17@mails.tsinghua.edu.cn>", "赵成钢 <zhaocg17@mails.tsinghua.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_system_allocator = "0.3.9"